---
- name: Install Snap packages classic mode
  become: true
  snap:
    name: 
      - code 
      - skype
      - spotify
    classic: yes
  when: absible_facts['packages'] == 'snapd'

- name: Install Snap packages
  become: true
  snap:
    name:
      - postman
      - vlc
      - mailspring
  when: absible_facts['packages'] == 'snapd'
