---
apps:
  - software-properties-common
  - webp
  - curl
  - fzf
  - git
  - htop
  - imagemagick
  - jq
  - nmap
  - tldr
  - tor
  - tree
  - wget
  - yamllint
  - unzip
  - bat
  - fd-find
  - fonts-firacode
  - gnome-tweak-tool
  - chrome-gnome-shell
  - translate-shell
  - python3-pip
  - snapd

  # Rust
  - exa
  - bat
  - delta

  # Neovim
  - neovim
  - ripgrep

  # Node
  - nodejs
  - yarn
  - npm

  # Docker
  - docker
