---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: 'var_user'
      prompt: 'local user name'
      default: 'root'
      private: no

  vars_files:
    - vars/variables.yml

  roles:
    - {role: 'common', tags: 'common'}
    - {role: 'packages', tags: 'packages'}
    - {role: 'snap', tags: 'snap'}
    - {role: 'python', tags: 'python'}
    - {role: 'git', tags: 'git'}
    - {role: 'ssh', tags: 'ssh'}
    - {role: 'zsh', tags: 'zsh'}
    - {role: 'tmux', tags: 'tmux'}
    - {role: 'node', tags: 'node'}
    - {role: 'nvim', tags: 'nvim'}
    - {role: 'alacritty', tags: 'alacritty'}
    - {role: 'docker', tags: 'docker'}

  post_tasks:
    - name: Restart
      become: true
      shell: sleep 2 && /sbin/shutdown -r now "Env automation completed"
      async: 1
      poll: 0
