---
- hosts: localhost
  connection: local

  vars:
    IOSEVKA_VERSION: 17.1.0
    SLACK_VERSION: 4.29.149
    DOCKER_DESKTOP_VERSION: 4.16.2

  vars_prompt:
    - name: 'USER_FULLNAME'
      prompt: 'User full name'
      private: no

    - name: 'USER_EMAIL'
      prompt: 'User email'
      private: no

  roles:
    - {role: 'common', tags: 'common'}
    - {role: 'packages', tags: 'packages'}
    - {role: 'python', tags: 'python'}
    - {role: 'git', tags: 'git'}
    - {role: 'ssh', tags: 'ssh'}
    - {role: 'zsh', tags: 'zsh'}
    - {role: 'tmux', tags: 'tmux'}
    - {role: 'node', tags: 'node'}
    - {role: 'nvim', tags: 'nvim'}
    - {role: 'alacritty', tags: 'alacritty'}
    - {role: 'docker', tags: 'docker'}

  post_tasks:
    - name: Restart
      become: true
      shell: sleep 2 && /sbin/shutdown -r now "Env automation completed"
      async: 1
      poll: 0
