---
- name: Make sure default tools are installed
  apt:
    name:
      - gnupg
      - software-properties-common
      - curl
      - ca-certificates
      - apt-transport-https
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true

- name: Add the key for the 1Password apt repository
  become: true
  apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
    state: present

- name: Add the 1Password apt repository
  become: true
  template:
    src: 1password.list.j2
    dest: /etc/apt/sources.list.d/1password.list

- name: Add 1passord folder pol
  become: true
  file:
    path: /etc/debsig/policies/AC2D62742012EA22/
    state: directory

- name: Add the debsig verify policy pol
  become: true
  get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol

- name: Add 1passord folder gpg
  become: true
  file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory

- name: Add the debsig verify policy gpg
  become: true
  apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    state: present

- name: Install Slack
  become: true
  apt:
    deb: 'https://downloads.slack-edge.com/releases/linux/{{ SLACK_VERSION }}/prod/x64/slack-desktop-{{ SLACK_VERSION }}-amd64.deb'

- name: Add Docker official GPG key
  become: true
  shell: "sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

- name: Add the Docker apt repository
  become: true
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  become: true
  apt:
    deb: 'https://desktop.docker.com/linux/main/amd64/docker-desktop-{{ DOCKER_DESKTOP_VERSION }}-amd64.deb'

- name: Install rust
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"

- name: Configure Nodejs LTS
  become: true
  shell: "curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -"

- name: Make sure apt packages are installed
  become: true
  apt:
    name: '{{ apps }}'
    state: latest
    update_cache: true
