---
- name: Make sure apt packages are installed
  become: true
  apt:
    name: '{{ apps }}'
    state: latest
    update_cache: true

- name: Install rust
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"

- name: install exa
  shell:  ~/.cargo/bin/cargo install exa