- name: Install APT packages
  apt:
    pkg:
      - software-properties-common
      - curl
      - htop
      - webp
      - imagemagick
      - bat
      - fd-find
      - fzf
      - nmap
      - ripgrep
      - tree
      - fonts-firacode
      - gnome-tweak-tool
      - gnome-boxes
      - qtile
      - chrome-gnome-shell
    state: present
    update_cache: yes