---
- name: Download pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install PIP
  become: true
  command: python3 /tmp/get-pip.py

- name: Install python packages
  become: true
  pip:
    name: pipenv
    executable: pip3
    state: latest
  with_items:
    - pipenv
    - virtualenv
    - twine