- name: Make sure .ssh folder exists
  file:
    path: '~/.ssh'
    state: directory

- name: Make sure ssh-key is generated
  openssh_keypair:
    path: '~/.ssh/id_rsa'
    type: ed25519
    size: 4096
    comment: "{{ USER_EMAIL }}"