- name: Make sure tmux is present
  apt:
    pkg:
      - tmux
      - xsel
  state: present

- name: Make sure config folders are present
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '~/.config/.tmux'
    - '~/.config/.tmux/plugins'

- name: Make sure tmp is present
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: '~/.config/.tmux/plugins/tpm'
    depth: 1

- name: Make sure .tmux.conf is present
  template:
    src: templates/.tmux.conf.j2
    dest: '~/.tmux.conf'