---
- name: Make sure nvm folder present
  file:
    path: ~/.nvm
    state: directory

- name: Install npm package globally.
  become: true
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
  - eslint