- name: Make sure nvm folder present
  file:
    path: ~/.nvm
    state: directory

- name: Install npm package globally.
  npm:
    name: 
      - neovim
      - eslint
      - sass-lint
    global: yes