- name: Set up sudo for the user
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: "{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD: ALL"

- name: Instaling Iosevka
  become: true
  command: './install-fonts.sh {{ IOSEVKA_VERSION }}'
  args:
    chdir: /tmp/env-automation/scripts/
