- name: Set up sudo for the user
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: "{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD: ALL"

- name: Ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Iosevka exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/iosevka-*.ttf"
  register: iosevka_exists
  ignore_errors: yes

- name: Download Iosevka
  when: iosevka_exists is failed
  get_url:
    url: "https://github.com/be5invis/Iosevka/releases/download/v{{ IOSEVKA_VERSION }}/ttf-iosevka-{{ IOSEVKA_VERSION }}.zip"
    dest: "/tmp/"
  timeout: 1800
  retries: 10
  delay: 3
  register: result
  until: result is succeeded
  no_log: false
  ignore_errors: True

- name: Unzip Iosevka
  when: iosevka_exists is failed
  ansible.builtin.unarchive:
    src: "/tmp/ttf-iosevka-{{ IOSEVKA_VERSION }}.zip"
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"

- name: Refresh font cache
  when: iosevka_exists is failed
  become: true
  command: fc-cache -fv