---
- name: Adding existing user "{{ lookup('env','USER') }}" to group docker
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes

- name: Make sure docker service is running
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes