---
- name: install Alacritty
  become: true
  shell: cargo install alacritty

- name: Make sure config directory is present
  file:
    path: ~/.config/alacritty
    state: directory

- name: Make sure config file is present
  template:
    src: templates/alacritty.yml.j2
    dest: ~/.config/alacritty/alacritty.yml
