---
- name: Check if the python3_venv is present
  stat:
    path: '{{ python3_venv_path }}'
  register: python3_venv_present

- name: Make sure venvs are created for python3
  shell: |
    virtualenv -p python3 {{ python3_venv_path }}
  when: not (python3_venv_path)

- name: Make sure neovim libs are intalled to python3 venv
  pip:
    virtualenv: '{{ python3_venv_path }}'
    virtualenv_python: python3
    name: '{{ python3_libs }}'
    state: present
